#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMITS_SINCE_PUSH=$(git log --pretty=oneline @{push}.. | wc -l)

if [ "$COMMITS_SINCE_PUSH" -gt 5 ]; then
  echo "";
  echo "\t\033[0;36mYou have made several commits since your last push.\033[0m";
  echo "\t\033[0;36mTo ensure your code passes all checks, push your changes or run \`pnpm all\`.\033[0m";
  echo "";
fi